#!/bin/bash

usage() {
  echo "Usage:"
  echo "  $0 sync [prod/stage]"
  echo "  $0 ls-service [current/latest]"
  echo "  $0 prepare/upgrade [service_name]"
  echo "  $0 start/stop/restart/down [service_name]"
}

sync() {
  (cd ${work_dir}/daocloud-release; git pull)
  rm -rf ${work_dir}/latest
  cp -r ${work_dir}/daocloud-release/$1 ${work_dir}/latest
}

join() {
  result=""
  for arg in $*
  do
    result="${result} -f ${arg}"
  done
  echo ${result}
}

service_exist() {
  [ -d ${work_dir}/$1/$2 ]
}

list_service() {
  for svc in `ls ${work_dir}/$1`
  do
    echo ${svc}
  done
}

prepare_service() {
  set -e
  tmpfile=`mktemp`
  for yml in `ls ${work_dir}/latest/$1/*.yml`
  do
    python ${base_dir}/parse_yml.py ${yml} > ${tmpfile}
    while read line
    do
      ip=`echo $line | cut -d " " -f1 | sed "s/-/./g"`
      image=`echo $line | cut -d " " -f2`
      export DOCKER_HOST=${ip}:${docker_port}
      if ! docker inspect ${image} > /dev/null; then
        docker login -u ${daocloud_user} -p ${daocloud_password} -e ${daocloud_email} daocloud.io
        docker pull ${image}
      fi
      unset DOCKER_HOST
    done < ${tmpfile}
  done

  rm -rf ${work_dir}/latest/$1/restart.list.tmp

  if [ -d ${work_dir}/latest/$1/config ]; then
    for conf in `ls ${work_dir}/latest/$1/config`
    do
      need_restart="no"
      if [ -f ${work_dir}/current/$1/config/${conf} ]; then
        if diff ${work_dir}/latest/$1/config/${conf} ${work_dir}/current/$1/config/${conf} > /dev/null; then
          continue
        else
          need_restart="yes"
        fi
      fi

      python ${base_dir}/parse_config_file.py ${conf} ${work_dir}/latest/$1/*.yml > ${tmpfile}
      while read line
      do
        svc=`echo $line | cut -d " " -f1`
        ip=`echo $line | cut -d " " -f2 | sed "s/-/./g"`
        remote_path=`echo $line | cut -d " " -f3`
        scp ${work_dir}/latest/$1/config/${conf} root@${ip}:${remote_path}

        if [ "${need_restart}" = "yes" ]; then
          if [ -f ${work_dir}/latest/$1/restart.list.tmp ]; then
            echo ${svc} >> ${work_dir}/latest/$1/restart.list.tmp
          else
            echo ${svc} > ${work_dir}/latest/$1/restart.list.tmp
          fi
        fi
      done < ${tmpfile}
    done
  fi

  set +e
}

upgrade_service() {
  set -e
  export DOCKER_HOST=${dce_host}
  up_latest_service $1

  sleep 1

  if [ -f ${work_dir}/latest/$1/restart.list.tmp ]; then
    for svc in `cat ${work_dir}/latest/$1/restart.list.tmp`
    do
      docker-compose `join ${work_dir}/latest/$1/*.yml` restart ${svc}
    done
  fi

  mkdir -p ${work_dir}/bak
  [ -d ${work_dir}/current/$1 ] && mv ${work_dir}/current/$1 ${work_dir}/bak/`date +%F_%T`
  cp -r ${work_dir}/latest/$1 ${work_dir}/current/$1
  rm -rf ${work_dir}/current/$1/restart.list.tmp

  unset DOCKER_HOST
  set +e
}

up_latest_service() {
  set -e
  export DOCKER_HOST=${dce_host}
  docker-compose `join ${work_dir}/latest/$1/*.yml` up -d --remove-orphans
  unset DOCKER_HOST
  set +e
}

down_service() {
  set -e
  export DOCKER_HOST=${dce_host}
  docker-compose `join ${work_dir}/current/$1/*.yml` down
  unset DOCKER_HOST
  set +e
}

start_service() {
  set -e
  export DOCKER_HOST=${dce_host}
  docker-compose `join ${work_dir}/current/$1/*.yml` start
  unset DOCKER_HOST
  set +e
}

stop_service() {
  set -e
  export DOCKER_HOST=${dce_host}
  docker-compose `join ${work_dir}/current/$1/*.yml` stop
  unset DOCKER_HOST
  set +e
}

restart_service() {
  set -e
  export DOCKER_HOST=${dce_host}
  docker-compose `join ${work_dir}/current/$1/*.yml` restart
  unset DOCKER_HOST
  set +e
}

#
# main
#

[ $# -lt 1 ] && usage && exit 1

base_dir=`dirname $0`
work_dir="${base_dir}/.."
dce_host="10.10.222.178:2375"
docker_port="12376"
daocloud_user="haipeng"
daocloud_password="wuhp2000"
daocloud_email="haipeng.wu@daocloud.io"

op=$1
shift

case ${op} in
  sync)
    if [ "$1" != "prod" -a "$1" != "stage" ]; then
      echo "ERROR: invalid op $1!"
      exit 1
    fi
    sync $1
  ;;
  ls-service)
    arg=$1
    if [ "$1" = "" ]; then
      arg="current"
    fi

    if [ ! -d "${work_dir}/${arg}" ]; then
      echo "ERROR: no ${arg} service!"
      exit 1
    fi

    list_service $arg
  ;;
  prepare|upgrade)
    if ! service_exist latest $1; then
      echo "ERROR: latest service $1 not found!"
      exit 1
    fi
    ${op}_service $1
    [ $? -eq 0 ] && echo "[   OK   ]   ${op}   service=$1" || echo "[ Failed ]   ${op}   service=$1"
  ;;
  start|stop|restart|down)
    if ! service_exist current $1; then
      echo "ERROR: current service $1 not found!"
      exit 1
    fi
    ${op}_service $1
    [ $? -eq 0 ] && echo "[   OK   ]   ${op}   service=$1" || echo "[ Failed ]   ${op}   service=$1"
  ;;
  *)
    usage
    exit 1
  ;;
esac
